name: Build and Deploy to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'
            - name: Install dependencies
              run: npm i
            - name: Build application
              run: npm run build:github
            - name: Set git email
              run: git config --global user.email "crewsquirrel@gmail.com"
            - name: Set git username
              run: git config --global user.name "0xIG"
            - name: Deploy to GitHub Pages
              run: npm run deploy:github
